import "./Details.css"
import InfoCard from "../InfoCard"
import  search from "../../assets/search.png"
import  select from "../../assets/select.png"
import  standout from "../../assets/standout.png"


export default function Details() {
  const cardDetails = [
    {
        id: 1,
        imageUrl: search,
        headingText: "Search",
        description: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    },
    {
        id: 2,
        imageUrl: select,
        headingText: "Select",
        description: "Choose from thousands of options generated by the slogan maker that fit your needs.",
    },
    {
        id: 3,
        imageUrl: standout,
        headingText: "Stand out",
        description: "Congrats on your new slogan. It's time to win the world!",
    },
  ]
  return (
    <div className="details-container">
        <div className="details">
            {cardDetails.map((card) => (
                <InfoCard
                    className="details-card"
                    key={card.id}
                    imageUrl={card.imageUrl}
                    headingText={card.headingText}
                    description={card.description}
                />
            ))}
        </div>
    </div>
  )
}
